$src = $pwd
$installDir = Join-Path $src '..' 'install'
$build = Join-Path $src 'build'
New-Item -ItemType Directory -Force -Path $build | Out-Null
Push-Location $build

cmake `
  -DCMAKE_BUILD_TYPE=Release `
  "-DCMAKE_INSTALL_PREFIX=$installDir" `
  "-DBUILD_LIST=core,imgproc,imgcodecs" `
  -DBUILD_SHARED_LIBS=OFF `
  -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_EXAMPLES=OFF `
  -DBUILD_JAVA=OFF -DBUILD_PACKAGE=OFF `
  -DOPENCV_FORCE_3RDPARTY_BUILD=ON `
  -DCMAKE_DISABLE_FIND_PACKAGE_TIFF=ON `
  -DBUILD_ZLIB=ON -DBUILD_JPEG=ON -DBUILD_PNG=ON -DBUILD_TIFF=ON `
  -DBUILD_OPENJPEG=ON -DBUILD_WEBP=ON `
  -DWITH_OPENEXR=ON -DBUILD_OPENEXR=ON `
  -DWITH_IPP=OFF `
  -DWITH_AVIF=OFF `
  -DWITH_ITT=OFF -DWITH_TBB=OFF -DWITH_OPENMP=OFF `
  -DWITH_OPENCL=OFF -DWITH_OPENVX=OFF `
  -DWITH_FFMPEG=OFF -DWITH_GSTREAMER=OFF -DWITH_1394=OFF -DWITH_V4L=OFF `
  -DWITH_QT=OFF -DWITH_GTK=OFF -DWITH_JASPER=OFF `
  -DWITH_LAPACK=OFF -DWITH_OPENBLAS=OFF -DWITH_EIGEN=OFF `
  -DWITH_ADE=OFF -DWITH_PROTOBUF=OFF -DWITH_VTK=OFF `
  -DBUILD_opencv_highgui=OFF `
  -DBUILD_opencv_python3=OFF `
  -DBUILD_opencv_python2=OFF `
  -DOPENCV_IO_FORCE_OPENEXR=ON `
  -DBUILD_WITH_STATIC_CRT=OFF `
  ..
cmake --build . --config Release
cmake --install . --config Release